SECRET_KEY='DJANGO-KEY'
DEBUG=True
ALLOWED_HOSTS="127.0.0.1 localhost"

PAYMENT_WEBHOOK_SECRET_KEY="PAYMENT_KEY"

PG_DATABASE="DATABASE-NAME"
PG_USER="DATABASE-USER-NAME"
PG_PASSWORD="DATABASE-PASSWORD"
DB_HOST="DATABASE-HOST"
DB_PORT="DATABASE-HOST"

EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT="EMAIL-PORT"
EMAIL_HOST_USER="EMAIL_HOST_USER-NAME"
EMAIL_HOST_PASSWORD="EMAIL_HOST_PASSWORD"

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY="SOCIAL_AUTH_GOOGLE_OAUTH2_KEY"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET="SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET"

